# Site settings
title: Judaica
#email: your-email@domain.com
description: blog
baseurl: "/judaica" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
highlighter: rouge
markdown_ext: "markdown,mkdown,mkdn,mkd,md,mmd"

permalink: pretty

social:
- platform: "facebook"
  user: "jaapcramer"
- platform: "twitter"
  url: "twitter.com"
  user: "jaapcramer"
- platform: "soundcloud"
  user: "jaapcramer"
- platform: "youtube"
  url: "youtube.com"
  user: "jaapcramer"
- platform: "instagram"
  url: "instagram.com"
  user: "jrcramer84"
- platform: "github"
  url: "github.com"
  user: "jrcramer"