# Site settings
title: Judaica
#email: your-email@domain.com
description: blog
baseurl: "/judaica" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jaapcramer
github_username:  jrcramer

# Build settings
markdown: kramdown
highlighter: rouge
markdown_ext: "markdown,mkdown,mkdn,mkd,md,mmd"
